services:
  postgres:
    image: postgres:15
    container_name: library_postgres
    environment:
      POSTGRES_DB: library_api_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rails:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      DATABASE_HOST: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      RAILS_MASTER_KEY: 10c389bfe3d4b0e378b5e909c32fbe01
    ports:
      - "3000:3000"
    volumes:
      - ./library-api:/rails
    depends_on:
      - postgres

  frontend:
    build:
      context: ./library-frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:3000
    container_name: library_frontend
    ports:
      - "3001:80"
    depends_on:
      - rails

volumes:
  postgres_data:
